### PR TITLE
[REG v0.6.0] (shared) static ctor/dtor are missing location information

### PR DESCRIPTION
**Pull request by mathias-lang-sociomantic**
Regression introduced in v0.6.0 by commit 082d09d3e78d0a2d24fd24ea8987c4cc66eedfff

### CODE REVIEW

**Comment by mathias-lang-sociomantic** [comment]
Ping

**Comment by Hackerpilot** [comment]
Sorry. I've been pretty busy lately.

**Comment by mathias-lang-sociomantic** [comment]
Thanks !

**Comment by mathias-lang-sociomantic** [comment]
May I also ask for a release ? :)
I couldn't find any other issue using master.

**Comment by mathias-lang-sociomantic** [comment]
Ping

**Comment by Hackerpilot** [comment]
https://github.com/Hackerpilot/libdparse/releases/tag/v0.7.0-alpha.13

**Pull request merged**
