### PR TITLE
Fix issue #71 - Parsing error on `someObject.new InnerClass`

### PR DESCRIPTION
**Pull request by mathias-lang-sociomantic**
Fixes hackerpilot/libdparse#71

### CODE REVIEW

**Comment by mathias-lang-sociomantic** [comment]
I guess it needs an update to the function's documentation, though I wouldn't mind a hand on that :)

**Comment by mathias-lang-sociomantic** [comment]
Ping.

**Comment by Hackerpilot** [comment]
Sorry for the delay. I've been busy with traveling and other things. I think adding this line to the doc comment should document the grammar change:

```
| $(RULE unaryExpression) $(LITERAL '.') $(RULE newExpression)
```

**Comment by mathias-lang-sociomantic** [comment]
Thanks !
Updated:

```diff
diff --git a/src/dparse/parser.d b/src/dparse/parser.d
index 9e40f0f..2156ed0 100644
--- a/src/dparse/parser.d
+++ b/src/dparse/parser.d
@@ -6236,6 +6236,7 @@ class Parser
      *     | $(RULE functionCallExpression)
      *     | $(RULE indexExpression)
      *     | $(LITERAL '$(LPAREN)') $(RULE type) $(LITERAL '$(RPAREN)') $(LITERAL '.') $(RULE identifierOrTemplateInstance)
+     *     | $(RULE unaryExpression) $(LITERAL '.') $(RULE newExpression)
      *     | $(RULE unaryExpression) $(LITERAL '.') $(RULE identifierOrTemplateInstance)
      *     | $(RULE unaryExpression) $(LITERAL '--')
      *     | $(RULE unaryExpression) $(LITERAL '++')
```

**Pull request merged**
